# @see: https://docs.travis-ci.com/
os: osx
install:
- brew install google-sparsehash zlib
env:
- PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig
before_script:
- git submodule update --init
script:
- mkdir build
- cd build
- cmake ..
- make V=1 VERBOSE=1
- make V=1 VERBOSE=1 install/fast DESTDIR=../destroot
- ../destroot/usr/local/bin/afsctool -cfvv -J2 -S -L .
- ../destroot/usr/local/bin/afsctool -vvv /Applications
